### ISSUE TITLE
F01_US01-Création de compte

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#1]
## US

En tant que futur utilisateur de la plateforme,
Je peux créer un compte sur l’application,
Afin de bénéficier des services de la plateforme.

### Cas nominal 🟢

**Étant donné** un nouveau visiteur sur le site internet qui est sur le formulaire de connexions
**Quand** il clique sur `Créer un nouveau compte`
**Alors** il accède au formulaire pour créer un nouveau utilisateur.

**Étant donné** un nouveau visiteur sur le site internet qui a remplie les champs du formulaire d'inscription avec des valeurs correct
**Quand** il clique sur `Créer un nouveau compte`
**Alors** un nouveau utilisateur est créer et il accède aux service du site.

### Cas limite 🟡

**Étant donné** un nouveau visiteur sur le site internet qui a remplie les champs du formulaire d'inscription avec des valeurs INcorrecte
**Quand** il clique sur `Créer un nouveau compte`
**Alors** il est renvoyé sur le formulaire de connexion avec un message d'erreur et aucun nouveau utilisateur n'est créer.

**Étant donné** un nouveau visiteur sur le site internet qui a remplie les champs du formulaire d'inscription
**Quand** il clique sur `Annuler`
**Alors** il est renvoyé sur le formulaire de connexion et aucun nouveau utilisateur n'est créer.

**Étant donné** un nouveau visiteur sur le site internet qui a remplie les champs du formulaire d'inscription avec des valeurs correct mais qu'elle correspond à un utilisateur déjà présent sur le site
**Quand** il clique sur `Créer un nouveau compte`
**Alors** il est renvoyé sur le formulaire de création avec un message d'erreur.

### Cas d'erreur 🔴

**Étant donné** un nouveau visiteur sur le site internet mais la base de donnée est inaccessible
**Quand** il clique sur `Créer un nouveau compte`
**Alors** il est renvoyé sur le formulaire de connexion avec un message d'erreur et aucun nouveau utilisateur n'est créer.

**Comment by Francois389** [comment]
Ajout des test d'acceptation

**Comment by quentinformatique** [comment]
peut etre explqiuer comment on arrive sur la page pour creer son compte

**Comment by Francois389** [comment]
Il manque deux cas limites : 
- Quand il clique sur Annuler
- Si le compte existe déjà
