### ISSUE TITLE
F02_US06-Accès à la liste des spectacles

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#10]
## US

En tant qu’organisateur d’au moins un festival,
Je peux accéder à la liste des spectacles,
Afin de pourvoir sélectionner les spectacles que je veux intégrer dans le festival.

### Cas nominal

**Étant donné** un organisateur de festival connecté qui souhaite accéder à la liste des spectacles pour son festival,
**Quand** il clique sur le bouton `Spectacles ...` de son festival
**Alors** il accède à la page de la liste des spectacles.

**Étant donné** un organisateur de festival sur la page de la liste des spectacles,  il sélectionne les spectacles à intégrer dans le festival,
**Quand** puis clique sur valider
**Alors** les spectacles choisis sont enregistrés avec succès.

**Étant donné** un organisateur de festival sur la page de la liste des spectacles,
**Quand** il a enregistré avec succès les spectacles choisis,
**Alors** les spectacles sont intégrés dans le festival.

### Cas limite

**Étant donné** un organisateur de festival connecté,  mais aucun spectacle n'est disponible,
**Quand** il accède à la liste des spectacles
**Alors** un message indiquant qu'aucun spectacle n'est disponible est affiché.

**Étant donné** un organisateur de festival connecté, qui sélectionne aucun des spectacles à intégrer dans le festival, 
**Quand** il clique sur valider
**Alors** un message d'information indiquant qu'au moins un spectacle doit être sélectionné devrait être affiché.

### Cas d'erreur

**Étant donné** un organisateur de festival connecté mais il y a une erreur côté serveur,
**Quand** il souhaite accéder à la liste des spectacles,
**Alors** un message d'erreur lui est affiché.

**Comment by quentinformatique** [comment]
Ajout des tests d'acceptation
