### ISSUE TITLE
F01_US02-Authentification

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#2]
## US

En tant qu’utilisateur ayant un compte sur la plateforme,
Je veux m’authentifier avec un login et un mot de passe,
Pour avoir accès à mes services personnalisés.

### Cas nominal 🟢

**Étant donné** un utilisateur connu, sur le site internet qui a remplie les champs du formulaire de connexion avec son login et mot de passe correct
**Quand** il clique sur `Se connecter`
**Alors** il est connecter et accède à ses services

### Cas limite 🟡

**Étant donné** un utilisateur connu, sur le site internet qui a remplie les champs du formulaire de connexion avec son login et mot de passe INcorrect
**Quand** il clique sur `Se connecter`
**Alors** il est renvoyer sur le formulaire de connexions avec un message d'erreur.

### Cas d'erreur 🔴

**Étant donné** un utilisateur connu, sur le site internet mais la base de donnée est inaccessible
**Quand** il clique sur `Se connecter`
**Alors** il est renvoyé sur le formulaire de connexion avec un message d'erreur.

**Comment by Francois389** [comment]
Ajout des test d'acceptation

**Comment by quentinformatique** [comment]
pareil que pour la 1ere US, expliquer comment il arrive sur la page de connexion

**Comment by Francois389** [comment]
Cas limite manquant :
- Annuler
