### ISSUE TITLE
F01_US03-Modification de mes données personnelles

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#3]
## US

En tant qu’utilisateur authentifié,
Je veux modifier mes données personnelles,
Pour maintenir à jour mes données en cas de changements dans ma vie

### Cas nominal 🟢

**Étant donné** un utilisateur connecté et est présent sur le formulaire modification en ayant modifier ses informations de manière correct
**Quand** il clique sur `Modifier mes informations`
**Alors** il est renvoyé sur le formulaire de modification avec un message de confirmation et ses informations sont modifié

### Cas limite 🟡

**Étant donné** un utilisateur connecté et est présent sur le formulaire modification en ayant modifier ses informations de manière INcorrect
**Quand** il clique sur `Modifier mes informations`
**Alors** il est renvoyé sur le formulaire de modification avec un message d'erreur

**Étant donné** un utilisateur connecté et est présent sur le formulaire modification qui n'a pas modifier les champs
**Quand** il clique sur `Modifier mes informations`
**Alors** il est renvoyé sur le formulaire de modification avec un message de confirmation

**Étant donné** un utilisateur connecté et est présent sur le formulaire modification qu'il est saisie ou non des valeurs dans les champs.
**Quand** il clique sur `Annuler`
**Alors** il est renvoyé sur le formulaire de modification avec un message de confirmation et aucune modification n'a été effectué.

### Cas d'erreur 🔴

**Étant donné** un utilisateur connecté et est présent sur le formulaire modification mais la base de donnée est déconnecté
**Quand** il clique sur `Modifier mes informations`
**Alors** il est renvoyé sur le formulaire de modification avec un message d'erreur

**Comment by Francois389** [comment]
Ajout des test d'acceptation

**Comment by Francois389** [comment]
Cas limite maquant : 
- Annuler
