### ISSUE TITLE
F01_US04-Désinscription

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#4]
## US

En tant qu’utilisateur authentifié,
Je veux supprimer mon compte de la plateforme,
Pour ne pas laisser trainer des informations personnelles sur une plateforme dont je ne veux plus bénéficier des services.

### Cas nominal 🟢

**Étant donné** un utilisateur connecté, et est présent sur la page des paramètres, 
**Quand** il clique sur le bouton rouge `Supprimer mon compte`
**Alors** un demande de confirmation apparait.

**Étant donné** un utilisateur qui a cliqué sur le bouton rouge `Supprimer mon compte` et que la demande de confirmation est apparu.
**Quand** il clique sur le bouton de confirmation rouge `Supprimer définitivement mon compte`
**Alors** le compte est supprimé de la base de donné et l'utilisateur est ramené à la page d'accueil.

### Cas limite 🟡

**Étant donné** un utilisateur qui a cliqué sur le bouton rouge `Supprimer mon compte` et que la demande de confirmation est apparu.
**Quand** il clique sur le bouton d'annulation `Annuler la suppression`
**Alors** le compte N'est PAS supprimé et l'utilisateur est de retour sur la page de paramètre

### Cas d'erreur 🔴

**Étant donné** un utilisateur qui a cliqué sur le bouton rouge `Supprimer mon compte` et que la demande de confirmation est apparu, mais que la base de donné est déconnecté
**Quand** il clique sur le bouton de confirmation rouge `Supprimer définitivement mon compte`
**Alors** le compte N'est PAS supprimé et l'utilisateur est de retour sur la page de paramètre avec un message d'erreur

## Pondération 🕓

5 heure

**Comment by Francois389** [comment]
Ajout des test d'acceptation

**Comment by quentinformatique** [comment]
on pourrait faire comme github quand on veut supprimer un dépot: on doit retaper le nom du dépot; on pourrait s'en inspirer en retapant son nom
