### ISSUE TITLE
F02_US01-Création d’un festival

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#5]
## US

En tant qu’utilisateur authentifié,
Je peux créer un nouveau festival dont je suis responsable sur l’application,
Afin de gérer les caractéristiques et la planification du festival.

### Cas nominal 🟢

**Étant donné** Un utilisateur authentifié sur la page d'accueil
**Quand** Il clique sur crée un festival
**Alors** un page de paramétrage de son festival lui est affichée

**Étant donné** Un utilisateur authentifié sur la page de création de festival, qui a rempli tout les champs correctement relatif au festival
**Quand** il clique sur valider
**Alors** le festival est crée, il est renvoyé sur la page récapitulative de l'utilisateur avec un message de confirmation

### Cas limite 🟡

**Étant donné** Un utilisateur authentifié sur la page de création de festival, et qu'il a rempli des champs incorrectement relatif au festival
**Quand** il clique sur valider
**Alors** le festival n'est pas crée, il est renvoyé sur la page de création d'un festival et message d'erreur détailler lui est affiché

### Cas d'erreur 🔴

**Étant donné** Un utilisateur authentifié sur la page de création de festival, qu' il a rempli les champs correctement relatif au festival  mais il y a une erreur coté serveur
**Quand** il clique sur valider
**Alors** le festival n'est pas crée, il est renvoyé sur la page de création d'un festival et message d'erreur détailler lui est affiché

## Pondération 🕓

15 heures

**Comment by quentinformatique** [comment]
test d'acceptation rédigés
