### ISSUE TITLE
F02_US02-Ajout d’un organisateur  au festival

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#6]
## US

En tant que responsable de festival,
Je peux affecter un nouvel organisateur du festival en renseignant le login ou l’email du nouvel organisateur ,
Afin de pourvoir gérer à plusieurs les caractéristiques et la planification du festival.

### Cas nominal 🟢

**Étant donné** un responsable de festival connecté,
**Quand** il souhaite ajouter un nouvel organisateur,
**Alors** il saisit le login ou l'email du nouvel organisateur et confirme l'affectation.

**Étant donné** un responsable de festival connecté, quil a affecté avec succès un nouvel organisateur,
**Quand** il clique sur valider
**Alors**  le nouvel organisateur est ajouté à la liste des organisateurs du festival.

**Étant donné** un responsable de festival connecté,
**Quand** il a affecté avec succès un nouvel organisateur,
**Alors** lorsqu'il consulte la liste des organisateurs, le nouvel organisateur est présent.

### Cas limite 🟡

**Étant donné**un responsable de festival connecté, qu'il tente d'ajouter un nouvel organisateur sans spécifier de login ou d'email,
**Quand** il clique sur valider
**Alors** un message d'erreur approprié devrait être affiché, indiquant que les informations du nouvel organisateur sont manquantes.

**Étant donné** un responsable de festival connecté, qu'il tente d'ajouter un nouvel organisateur avec un login ou un email déjà existant,
**Quand** il clique sur valider
**Alors** un message d'erreur approprié devrait être affiché, indiquant que le login ou l'email est déjà utilisé par un autre organisateur.

### Cas d'erreur 🔴

**Étant donné** un responsable de festival connecté mais il y a une erreur coté serveur
**Quand** il souhaite ajouter un nouvel organisateur,
**Alors** un message d'erreur lui est affiché

**Comment by quentinformatique** [comment]
ajout des tests d'acceptations

**Comment by Francois389** [comment]
- [ ] Dans le premier test d'acceptation (Cas nominal), mélange des catégorie, le Quand doit refléter une action pas une pensé
- [ ] Pareil pour le troisième test (Cas nominal) Une partie du Alors doit êtres dans le Quand
- [ ] Test du cas d'erreur le quand n'est pas trop explicite je trouve

**Comment by Francois389** [comment]
Modifier pour être en accord avec le prof.
On ajoute un organisateur avec son email.
Si il correspond à un utilisateur on l'ajoute, sinon on demande d'autre info
