### ISSUE TITLE
F02_US03-Modification des caractéristiques d’un festival

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#7]
## US

En tant qu’organisateur d’un festival,
Je peux modifier les caractéristiques du festival,
Afin de pouvoir reporter les changements relatifs à ce festival en lien avec des aléas.

### Cas nominal

**Étant donné** un organisateur de festival connecté,
**Quand** il souhaite modifier les caractéristiques du festival,
**Alors** il accède à la page de modification des caractéristiques du festival.

**Étant donné** un organisateur de festival sur la page de modification des caractéristiques, et qu'il apporte les modifications nécessaires,
**Quand** il clique sur modifier
**Alors** les changements sont enregistrés avec succès.

### Cas limite

**Étant donné** un organisateur de festival connecté, qu'il tente de modifier les caractéristiques sans apporter de changements,
**Quand** il clique sur valider  
**Alors** un message indiquant qu'aucune modification n'a été effectuée devrait s'afficher.

**Étant donné** un organisateur de festival connecté, qu'il modifie les caractéristiques du festival avec des valeurs incorrectes,
**Quand** il clique sur valider
**Alors** les changements ne sont pas enregistrés avec succès.

### Cas d'erreur

**Étant donné** un organisateur de festival connecté mais il y a une erreur côté serveur,
**Quand** il souhaite modifier les caractéristiques du festival,
**Alors** un message d'erreur lui est affiché.

**Comment by quentinformatique** [comment]
tests d'acceptations rédigés

**Comment by Francois389** [comment]
Manque message d'erreur et la redirection
