### ISSUE TITLE
F02_US04-Suppression d’un  festival

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#8]
## US

En tant que responsable d’un festival,
Je peux supprimer le festival,
Afin de ne pas laisser trainer des données qui ne sont plus utiles sur la plateforme.

### Cas nominal

**Étant donné** un responsable de festival connecté,
**Quand** il souhaite supprimer le festival,
**Alors** il accède à la page de suppression du festival.

**Étant donné** un responsable de festival sur la page de suppression,
**Quand** il confirme la suppression du festival,
**Alors** le festival est supprimé avec succès de la plateforme.

### Cas limite

**Étant donné** un responsable de festival connecté,
**Quand** il tente de supprimer le festival sans confirmation,
**Alors** un message de confirmation devrait être affiché avant la suppression effective.

**Étant donné** un responsable de festival connecté,
**Quand** il tente de supprimer le festival avec des données associées,
**Alors** un avertissement devrait être affiché, indiquant que certaines données pourraient être perdues avec la suppression du festival.

### Cas d'erreur

**Étant donné** un responsable de festival connecté mais il y a une erreur côté serveur,
**Quand** il souhaite supprimer le festival,
**Alors** un message d'erreur lui est affiché.

**Comment by quentinformatique** [comment]
tests d'acceptations rédigés

**Comment by Francois389** [comment]
- [ ] Le Étant donné sert à placer le décors. Il n'est pas bien fais pour le quatrième test ( CL )
