### ISSUE TITLE
F02_US05-Accès à la liste de mes  festivals

### ISSUE THREAD

**Issue by CrabeNeo** [GroupeSAETPA1/Festiplan#9]
## US

En tant qu’organisateur d’au moins un festival,
Je peux accéder à la liste des festivals dont je suis organisateur,
Afin d’accéder facilement à un festival sur lequel je dois travailler'.

### Cas nominal

**Étant donné** un organisateur de festival connecté,
**Quand** il souhaite accéder à la liste de ses festivals,
**Alors** il accède à la page de la liste des festivals.

**Étant donné** un organisateur de festival sur la page de la liste des festivals,
**Quand** il clique un festival,
**Alors** il est redirigé vers la page du festival sélectionné.

### Cas limite

**Étant donné** un organisateur de festival connecté sans festival associé,
**Quand** il accède à la liste des festivals,
**Alors** un message indiquant qu'aucun festival n'est associé à son compte devrait être affiché.

### Cas d'erreur

**Étant donné** un organisateur de festival connecté mais il y a une erreur côté serveur,
**Quand** il souhaite accéder à la liste de ses festivals,
**Alors** un message d'erreur lui est affiché.

**Comment by quentinformatique** [comment]
test d'acceptations rédigés

**Comment by Francois389** [comment]
Changer le premier site
